### ISSUE TITLE
Game freeze instead of throwing an error

### ISSUE THREAD

**Issue by JulienBe** [PurpleKingdomGames/indigo#110]
Hello !

Just started with indigo, so I don't know if it's intended or not, at least that doesn't seems right to me.

When taking the code from the pirate demo, and removing 

https://github.com/PurpleKingdomGames/indigo/blob/1b545f079c8bb872147f234aba234f8c7d2f45db/demos/pirate/src/main/scala/pirate/core/Assets.scala#L27

I was expecting to get an error at load time, probably a stacktrace.

Instead the game just keeps running at the end of the loading scene with the music running.

Again, totally new to indigo, just poking around. If there is a configuration or it's just specific to the pirate demo I apologize :)

**Comment by davesmith00000** [comment]
Hi @JulienBe - thanks for the report, I believe you've found an error case I've overlooked! :-)

Prior to the last release, Indigo had no particular error handling and the result of a missing asset was/is as you described. It probably tells you in the console that it couldn't find something, but I think you're quite right, these days those types of error cases should result in a crash error report.

Thanks again for bringing it to my attention. To debug this in the meantime, as I said above, I expect there will be a log line telling you it couldn't find something (hopefully).

**Comment by JulienBe** [comment]
Hmm I don't think so, unless there are logs somewhere else ? 

That's what I get in sbt:

~~~
sbt:pirate> runGame
[success] Total time: 0 s, completed Jan 20, 2021 12:06:09 AM
[success] Total time: 1 s, completed Jan 20, 2021 12:06:09 AM
/home/j/Dropbox/indigo/pirate/target/scala-3.0.0-M3

      //                  //  //
                         //
    //  //////      //////  //    ////      //////
   //  //    //  //    //  //  //    //  //    //
  //  //    //  ////////  //  ////////  //////
                                   //
                            //////

dirPath: /home/j/Dropbox/indigo/pirate/target/indigoBuild
Copying assets...
/home/j/Dropbox/indigo/pirate/target/indigoBuild/index.html
Starting 'The Cursed Pirate'

> indigo-runner@1.0.0 start /home/j/Dropbox/indigo/pirate/target/indigoRun
> electron .

(node:3067) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
~~~

**Comment by davesmith00000** [comment]
Try having a look at your browser's javascript console. If you're running in Electron (indigoRun) you can open the console from the menu bar or on a mac it's alt+cmd+i.

**Comment by JulienBe** [comment]
Ha ! Indeed if I display the console here it is :) Thanks !
