### ISSUE TITLE
Moving buttons is bothersome

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#128]
Fallout of reorganising the `SceneNode` hierarchy: `ButtonAssets` are now a `SceneNode` and have no standard methods to reposition them. You have to match on the sub-type and move that. 😒

**Comment by davesmith00000** [comment]
This can be improved. The position of the assets is set on draw based on the bounds. So basic commands like `moveTo` can be added and work on the bounds field.

**Comment by Sintrastes** [comment]
I've run into this as well. Currently making use of a helper method to get around this.
