### ISSUE TITLE
Buttons: Missing a "hold down" action.

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#133]
Should repeatedly fire events if the mouse is held down on the button.

**Comment by sylvansson** [comment]
Hey @davesmith00000, I can pick this up if you don't think it's too complex. 

At a quick glance, it looks like we could implement this by updating `Button.update` to no longer require a mouse press event to fire mousedown events and instead keep firing them as long as the button state is "down". But I think this might be a simplistic take, and that what you want is a new `onHoldDown` member to differentiate between events to fire when a button is clicked and when the user keeps the button pressed. Am I right?

Should these events fire on every frame tick, and should there be a threshold before we start firing them? If so, should these things be configurable?

**Comment by davesmith00000** [comment]
Hello, feel free!

The UI components need love in general, it's one of those areas I always plan to revisit when I have a concrete use case but rarely do.

I must warn you that the UI components can be deceptively fiddly! There should be some tests in place for them though. 🙂

I did mean the latter yes, a new onHoldDown action, and a configurable time delay might be nice but that means hold a time based bit of state which might be a pain. Also firing an event every frame means having access to the FrameTick event and I'm not sure it does currently?

Have a go if you like, see what you think. It sounds easy but might yet turn out to be difficult.

Dave

**Comment by sylvansson** [comment]
> Also firing an event every frame means having access to the FrameTick event and I'm not sure it does currently?

This really isn't my area of expertise so I might have used the wrong terminology, sorry. I was asking whether we should fire the events on every call to `Button.update` or every N calls but it sounds like perhaps that should be left to whoever's developing the game. Same thing for the time delay before we start firing events.

> I must warn you that the UI components can be deceptively fiddly!

Noted :-)

**Comment by davesmith00000** [comment]
I think the expected behaviour would be an action that is fired every frame that the button is being held down on. Which I'm pretty sure is what you were saying too. The catch is that means getting one update trigger per frame, and that would normally come from the `FrameTick` event. I haven't looked - it might be that the button has access to that already - I'm just not sure.
