### ISSUE TITLE
Rendering Faults on Windows

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#143]
This was reported during Ludlum Dare 48. Unfortunately I have no way to verify this at the moment...

The symptoms were:
1. A game was being made on a linux box, and all effects were showing up correctly. Specifically WebGL 2.0 renderer things like shapes.
2. When the game was passed over to the folks doing their art, they could never see the results, and it sounded to me like Indigo was falling back to WebGL 1.0.
3. However! According to Indigo's logs it was still using WebGL 2.0!
4. When the devs on the linux boxes set the `config.useWebGL1` flag, they got the same experience as their Windows based team mates.

Anything more to add @kag0?

**Comment by kag0** [comment]
Sounds about right, specifically it was shaders and shapes. All other graphics work fine.

You can still repro [here](https://kag0.github.io/ld48/dist), linux machines should show hitboxes while windows will not

**Comment by davesmith00000** [comment]
![image (17)](https://user-images.githubusercontent.com/908709/117649293-43bb9400-b187-11eb-9e6a-27743368a94a.png)

@hobnob has kindly verified that the WebGL 2 required params / requirements have all been met.

**Comment by davesmith00000** [comment]
Just a tiny update:

I think we've proved that actually the WebGL 2 detection is probably doing the right thing, so first theory debunked.

The new theory is that, unfortunately, I may be doing something in the shader code that doesn't work as expected on Windows machines. Just a guess.

Another test: Do clones work? Only supported by the WebGL 2.0 renderer _but_ don't do anything remotely clever with shaders.

**Comment by davesmith00000** [comment]
Hi @kag0,

So I've found and fixed one problem with Windows rendering and can't see any more at the moment. If you get a moment you could try it on this link:

https://davesmith00000.github.io/ld48/

This is it running on a Windows VM (didn't work originally):

<img width="752" alt="Screenshot 2021-05-19 at 21 25 20" src="https://user-images.githubusercontent.com/908709/118879844-1be7d100-b8e9-11eb-86af-f3436efed278.png">

Also, unrelated, I like the game! I only just worked out what it was about (I'd just been bug hunting previously) and it's a really nice idea! 😁

@hobnob is going to try it out again tomorrow to see if it works for him, so if you can't get anyone to test it, no worries.

**Comment by kag0** [comment]
yup, looks to be working for me on windows with ff

> Also, unrelated, I like the game!

haha, thanks, glad to hear it

**Comment by davesmith00000** [comment]
Fix will be in the next release.

**Comment by davesmith00000** [comment]
Copying the description from the PR in case anyone is looking for the details:

```
Essentially the max number of buffer bindings on the Windows machines we have access to is 24, but 24 is the _minimum_ number that the WebGL 2.0 detection process in Indigo looks for. So I was foolishly (oversight) checking for 24 to be available, and then instantly setting two pointers outside that range to 32 and 64 for the blend and custom UBO data bindings respectively.

This was not a problem on Mac or Linux, which is why it went undetected, but was immediately a problem when we tried it on Windows, even a Windows VM. At least, on the machines we have for testing.

The solution is simply to reduce Indigo's requirements by lowering the pointer offsets.
```
