### ISSUE TITLE
Introduce a "Spatial" typeclass

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#153]
There is a boring problem at the moment that you can't do something like:

```scala
def doWork[T <: RenderNode](node: T): T =
  node.moveTo(Point(10, 10))
```

To solve this currently, you have to match on every possible concrete type you support - yuk.

It would be nice to introduce a typeclass to allow something like this:

```scala
def doWork[T : Spatial](node: T): T =
  node.moveTo(Point(10, 10))
```

**Comment by bilki** [comment]
So, is this basically turning https://github.com/PurpleKingdomGames/indigo/blob/master/indigo/indigo/src/main/scala/indigo/shared/scenegraph/SpatialModifiers.scala into a typeclass, and give instances for every class extending from it? :thinking: Seems like a sensible approach, many (if not all) the implementations are there, it's a matter of moving them a proper place (companion object, instances object for all of them?) and fix the affected signatures by this change.

**Comment by davesmith00000** [comment]
That's pretty much the idea yes. That trait is literally only there to make sure I don't forget any implementations! The only thing to be aware of follow recent work, is the SceneNode splits into RenderNode, EntityNode and DependentNode (CompositeNode is gone) and they have some slight differences.

I also wondered if there is another typeclass that allows you to also affect the attributes common the SceneNode's and Clone classes.

**Comment by davesmith00000** [comment]
@bilki made a valiant attempt at this but we decided in the end that it created as many problems as it solved, and thought it best to leave it as is for now.
