### ISSUE TITLE
Unable to run snake demo

### ISSUE THREAD

**Issue by Iltotore** [PurpleKingdomGames/indigo#180]
Mill version: 0.9.9
OS: Windows 10
Node version: 14.17.4 (LTS)

I get the following error when trying to executing `mill -i snake.runGame`:
```scala
snake.indigoRun java.io.IOException: Cannot run program "npm" (in directory "C:\Users\rapha\Documents\indigo-examples\demos\snake\out\snake\indigoRun\dest"): CreateProcess error=2, Le fichier spécifié est introuvable
    java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    os.proc.proc$lzycompute$1(ProcessOps.scala:128)
    os.proc.proc$1(ProcessOps.scala:122)
    os.proc.spawn(ProcessOps.scala:135)
    os.proc.call(ProcessOps.scala:76)
    indigoplugin.IndigoRun$.run(IndigoRun.scala:32)
    millindigo.MillIndigo.$anonfun$indigoRun$2(MillIndigo.scala:60)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
java.io.IOException: CreateProcess error=2, Le fichier spécifié est introuvable
    java.lang.ProcessImpl.create(Native Method)
    java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
    java.lang.ProcessImpl.start(ProcessImpl.java:139)
    java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    os.proc.proc$lzycompute$1(ProcessOps.scala:128)
    os.proc.proc$1(ProcessOps.scala:122)
    os.proc.spawn(ProcessOps.scala:135)
    os.proc.call(ProcessOps.scala:76)
    indigoplugin.IndigoRun$.run(IndigoRun.scala:32)
    millindigo.MillIndigo.$anonfun$indigoRun$2(MillIndigo.scala:60)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

But NPM is installed and available in the Path. If I type `npm`, it is executed.

Note: "Le fichier spécifié est introuvable" means "No such file"

EDIT: Executing the command manually (`npm start`) works.

**Comment by davesmith00000** [comment]
Hello @Iltotore!

I've just had a quick go at re-creating the issue and it's working ok for me, we have some system differences, but can I ask you to try a different process first?

`indigoRun` is not a complete task by itself, you need to do `fastOpt` first. Happily there is a command alias in the project that looks like this:

```scala
  def runGame() = T.command {
    T {
      compile()
      fastOpt()
      indigoRun()()
    }
  }
```

So if you do `mill snake.runGame` on the command line it should do everything. Can you try it and see if it works?

I'm now on Mill 0.9.9, Mac, Node v16.6.0. So I guess the next thing would be to upgrade node and see if that helps - but this doesn't seem like a node version problem - just a hunch.

**Comment by Iltotore** [comment]
Hello @davesmith00000 
As you can see in the first post, I run `runGame` and I can confirm `fastOpt` was executed.

**Comment by davesmith00000** [comment]
My apologies @Iltotore!

We did have another person on our Gitter channel with a similar problem, who discovered the issue was that the way we're invoking electron in `indigoRun` doesn't work on Windows - although that person is using sbt. Could be the same problem? This person discovered it did work if executed via WSL I believe - may be worth a try?

Did you try it on Mill 0.9.8? Did it work there and not in 0.9.9?

Either way, thanks for reporting the issue. Window's bugs are a bit tricky for me to deal with but I shall try and replicate.

Cheers,

Dave

**Comment by Iltotore** [comment]
> We did have another person on our Gitter channel with a similar problem, who discovered the issue was that the way we're invoking electron in indigoRun doesn't work on Windows - although that person is using sbt. Could be the same problem? This person discovered it did work if executed via WSL I believe - may be worth a try?

Thank you for your support @davesmith00000!
If I execute manually the same exact command as invoked with `os.proc`, it works. I will test on WSL tomorrow and also try to solve this issue (I want to test Indigo for a Game Jam =p)

> Did you try it on Mill 0.9.8? Did it work there and not in 0.9.9?

I will also try 0.9.8 tomorrow.

Cheers.

**Comment by davesmith00000** [comment]
Excellent, let me know how you get on.

Which game jam if you don't mind me asking / if you're decided? If you join us on Discord (link on the repo readme, there's a gitter link there too but discord is better for this sort of thing) I'd be happy to answer questions if you get stuck.

Either way - good luck and thanks for trying Indigo out! :-)

**Comment by Iltotore** [comment]
> Which game jam if you don't mind me asking / if you're decided? 

It's a small french jam organized by ReadTheDocs called Read the Jam. If I'm stuck, I will join the server.

**Comment by Iltotore** [comment]
So @davesmith00000 I tested on different configurations without success:
- Windows:
  - 0.9.9: "Not found" (as described above)
  - 0.9.8: "Not found"
- WSL:
  - 0.9.8: Had to install packages using `npm install` and it still doesn't work because WSL is CLI but I think it is ok.
  
So it doesn't work on Windows and seems to work on linux **if I use npm install manually**.

**Comment by davesmith00000** [comment]
Ok, thank you for testing. I'll need to pull together a Windows dev environment somehow and work out what to do.

**Comment by ASRagab** [comment]
Can report nearly identical issue with sbt, after using `sbt new PurpleKingdomGames/indigo.g8` used most defaults can import and run `buildGame` successfully, but when running `runGame`

```shell
[error] (indigoRun) java.io.IOException: Cannot run program "npm" (in directory "C:\Users\...\Scala\DemoGame\target\indigoRun"): CreateProcess error=2, The system cannot find the file specified
```


SBT Version: 1.5.5
Windows version: 11
Node Version:  v14.18.1

However, can navigate to the `target\indigoRun` directory and `npm start` and I get the electron window with a rotating cube

**Comment by davesmith00000** [comment]
Thank you very much for confirming.

I've noticed there's an issue on the os-lib project with a similar exception report. I'm not clear if they're related yet, but it's a clue!
