### ISSUE TITLE
Add more built-in colours to RGBA & RGB

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#195]
We have a bunch of pre-made colours like `RGBA.White`. I frequently want more simple colours when I'm prototyping, like orange and purple! What else is there?

**Comment by ritschwumm** [comment]
https://en.wikipedia.org/wiki/X11_color_names maybe?

**Comment by davesmith00000** [comment]
<img width="495" alt="Screenshot 2021-09-26 at 21 19 25" src="https://user-images.githubusercontent.com/908709/134822841-681043ab-1420-4044-b75d-c1c7642ececd.png">

Seems to contain all of the important colours. 😁

**Comment by davesmith00000** [comment]
@sylvansson If you do have a go at this, I've pushed ALOT of changes today, make sure your repo is up to date. :-)

**Comment by Iltotore** [comment]
@sylvansson I'm not. You can commit it 😛

**Comment by sylvansson** [comment]
Awesome :-) I'll work on this this week.
