### ISSUE TITLE
Clip `.reverse.reverse` should play forwards

### ISSUE THREAD

**Issue by japgolly** [PurpleKingdomGames/indigo#269]
Hi! Was just perusing the source code for fun and noticed what seems to be a bug in `Clip`: https://github.com/PurpleKingdomGames/indigo/blob/691a3b9cede540f89f89bcf9445f1c37ffc03748/indigo/indigo/src/main/scala/indigo/shared/scenegraph/Clip.scala#L52-L53

I would expect that if I had a `Clip` instance set to play forwards, calling `.reverse` twice should result in it playing forwards again.

So I think the impl should be

```scala
  def reverse: Clip[M] = this.copy(playMode = playMode.reverse)
```

(and then add `.reverse` to `PlayMode` if it doesn't have it already)

**Comment by davesmith00000** [comment]
Hello!
Ah, I have fallen victim to semantics. 😄 
You are quite right, a functional programmer would read `.reverse.reverse` in terms of a `List` not a VCR!
Originally, there was only "play `forwards`" and "play `backwards`" and at the last minute in a moment of madness I thought "maybe people would understand reverse better than backwards? I'll add a delegate..." ...and here we are.
Thanks for bringing it to my attention, I'll ponder it and either make it work as you suggest or deprecate it.

**Comment by japgolly** [comment]
Ah! I didn't think of it in terms of a VCR at all (and I had to wrack on my old brain for a bit to remember having a VCR, hehe) and yeah I see what you mean now. Unambiguous language is hard :)

**Comment by davesmith00000** [comment]
Indeed, but I decided you were right In the end and fixed it accordingly - thanks for raising the issue. 👍
