### ISSUE TITLE
The injected element should be configurable

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/indigo#275]
At the moment it is a requirement of Indigo that an element with an id of `indigo-container` is present in the HTML. This limits users a little bit when creating their own HTML templates.

Indigo should allow the user to set the ID of the element that should be updated with Indigo, with the default value being the existing `indigo-container` string

**Comment by davesmith00000** [comment]
So you can now do the following (in JS or Scala, but there are also new Scala versions of the launch function):

```javascript
IndigoGame.launch("my-container", {"width": window.innerWidth.toString(), "height": window.innerHeight.toString()})
```

For a page with this in it:

```html
<div id="my-container"></div>
```

Will be in the next release.
