### ISSUE TITLE
Add support for mouse scroll bar events

### ISSUE THREAD

**Issue by Sintrastes** [PurpleKingdomGames/indigo#290]
A lot of games make use of this sort of input to event, so this is important to have. Some examples:

   * Zooming in and out
   * Scrolling up and down in a UI for a settings page
   * Toggling through the currently selected item in an item bar.

Some links from @bilki for some relevant docs: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent, https://developer.mozilla.org/en-US/docs/Web/API/Element/scroll_event

**Comment by davesmith00000** [comment]
I believe @bilki is looking into this? But let me know if that's not the case! 😄

**Comment by Sintrastes** [comment]
That would be good to know! I was under the impression he was just working on mouse click events, but I could be wrong. Don't want to duplicate work.

**Comment by bilki** [comment]
Yes, I'm working only the button click actions, as it was relatively easy to extend the current set of events. Adding the mouse wheel/scroll actions is a bit different, I'm not sure how much effort would it take, and it feels like #284 is already a self-contained change, we could tackle this other feature later in another PR.

**Comment by davesmith00000** [comment]
Apologies - didn't mean to give you more work there! 😅

**Comment by bilki** [comment]
I'm going to give this a try, give me a shout if you already implemented something 👀

**Comment by Sintrastes** [comment]
@bilki Nothing here yet. Go for it!

**Comment by bilki** [comment]
Solved in #308
