### ISSUE TITLE
Fix sbt reloading problem (see Tyrian fix)

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#299]
Requires a similar treatment to this one in Tyrian by @Angel-O

https://github.com/PurpleKingdomGames/tyrian/commit/e047c16310dbeca4c8774fe809b4d4476b44eba9

**Comment by Angel-O** [comment]
sure, let's see if we can fix it 🚀

**Comment by davesmith00000** [comment]
Oh, I wasn't suggesting you should do it. 😬😅

Help is always welcome, but only if you want to. No pressure! 🙂

**Comment by Angel-O** [comment]
no worries: having fun 😄  (also playing around with `Indigo` is on my TODO-list, so this is a good start)

**Comment by Angel-O** [comment]
[PR](https://github.com/PurpleKingdomGames/indigo/pull/305) 🚀

**Comment by davesmith00000** [comment]
Thanks @Angel-O 👍
