### ISSUE TITLE
Update UI components to remove deprecated mouse warnings

### ISSUE THREAD

**Issue by bilki** [PurpleKingdomGames/indigo#302]
As part of #283, a value in `Mouse` that stores the state for the left mouse button (whether it's down or not) was deprecated, triggering some warnings in UI components that use it.

Update UI components to use the new mouse buttons interface in `Mouse`.

**Comment by sylvansson** [comment]
Hey @bilki, did you plan on picking this up? I haven't looked at the relevant code yet but I'd be happy to take this on if you don't think it's too complex.

**Comment by bilki** [comment]
Go ahead, it shouldn't be too complex, but there's a few of them. If you need some help give me a shout.

**Comment by sylvansson** [comment]
Ok great :-)

**Comment by sylvansson** [comment]
If I understand correctly, all I need to do is replace [every use of `.leftMouseIsDown`](https://github.com/PurpleKingdomGames/indigo/search?q=leftmouseisdown) with either `.isLeftDown` or `.isButtonDown(MouseButton.LeftMouseButton)`. Is that correct? I assume I also need to remove the deprecation warnings, except in the class definition for `Mouse`:

https://github.com/PurpleKingdomGames/indigo/blob/98182bf57e94fe2be7ad23629bff09ee60872aca/indigo/indigo/src/main/scala/indigo/shared/input/Mouse.scala#L12-L17

If that's the case, the changes are already made and I should be able to submit a PR by tomorrow night.
