### ISSUE TITLE
resizeCanvas event broken.

### ISSUE THREAD

**Issue by laurensdv** [PurpleKingdomGames/indigo#321]
Hello,

The Window onresize canvas seems to be broken after updating to 0.11.1-SNAPSHOT (with the unchanged index.html) when doing indigo runGame for testing in 

```
electron:indigo-support.js:21 Uncaught TypeError: Cannot set properties of null (setting 'height')
    at resizeCanvas (indigo-support.js:21)
    at later (indigo-support.js:9)
```

something changed?

**Comment by davesmith00000** [comment]
Yes, there is another issue (poorly named): https://github.com/PurpleKingdomGames/indigo/issues/306

I think this is because I changed the way the canvas element is named but haven't accounted for that in the supporting JS.

**Comment by laurensdv** [comment]
Oh, yes, that's the one :-)
