### ISSUE TITLE
Add a `Tileset` helper

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#346]
This is a helper object that for a given texture that has been equally divided into regularly sized sub images, allows you to get a `Graphic` by index. E.g. a 64x64 image with 32x32 images on it could be accessed with indices 0, 1, 2, and 3.

**Comment by sylvansson** [comment]
I'd be happy to pick this one up :-)

**Comment by davesmith00000** [comment]
That would be great if you get the time. 😄

**Comment by sylvansson** [comment]
Huh, it looks like this was already implemented in https://github.com/PurpleKingdomGames/indigo/pull/350. It seems to only support `Material.Bitmap` and not `ImageEffects` though. I'm not sure what additional changes would be needed, if any, besides some user-facing documentation and updating some of the examples to use the class.
