### ISSUE TITLE
Snake demo does not work with Mill 0.10.2

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#355]
It looks like the fastOpt file has been renamed from `out.js` to `main.js`...?

**Comment by davesmith00000** [comment]
Followed up on this: Mill `0.10.3` is also not working but it's now a problem with the way Mill handles module kinds (`ESModule`/`CommonJSModule`).

Indigo has a PR ready to go that includes a less brittle method of finding the right file to use from the right location as described in the original comment.

@lolgab has a fix ready to go, just needs to be released.

Everyone should use Mill `0.10.0` until then.

**Comment by lolgab** [comment]
This will be fixed once https://github.com/com-lihaoyi/mill/pull/1851 is merged

**Comment by lolgab** [comment]
Mill `0.10.3-36-e038bb` contains the fix. Can you try to see if it solves your problem?

**Comment by davesmith00000** [comment]
Will do - will give it a shot this evening. 👍

**Comment by davesmith00000** [comment]
@lolgab Works perfectly 🎉 
Sorry about the delay coming back to you.

**Comment by lolgab** [comment]
No worries :)

**Comment by davesmith00000** [comment]
Fixed on main branch by upgrading to Mill 0.10.4, will go out with the next release.
