### ISSUE TITLE
(Re)Consider replacing `List` on the APIs

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#362]
It's currently very easy for someone to hit the performance limits of the engine with some fairly ordinary list manipulations.

I've considered this before but rejected it on the basis that list semantics are nice and friendly, but maybe a little pain is worth it.

The properties the data structure most needs is (I think):

1. Fast construction
2. Fast traverse
3. Fast concatenation
4. Minimal allocation

@sjrd has suggested `IArray` or possibly a custom data structure built on `IArray` such as a [Rope](https://en.wikipedia.org/wiki/Rope_(data_structure)).

**Comment by armanbilge** [comment]
Depending on your exact constraints ...

I wonder if this talk on `fs2.Chunk` (or `fs2.Chunk` itself) would be helpful to you.
https://youtu.be/wOybldcyMLs

There's also [`cats.data.Chain`](http://typelevel.org/cats/datatypes/chain.html).

**Comment by davesmith00000** [comment]
Interesting talk, thanks for sharing, some great details and considerations there. The binary search work that Michael talks about at the end is not dissimilar to the Rope suggestion it seems to me.

`Chain` feels closer to what I'm after than `Chunk` though, someone else also kindly recommended I look into it.

The interesting thing about this structure is that (famous last words...) I need almost no manipulation operations, as long as I can construct it and traverse it efficiently, that's basically all I need. It can be rather specialised.

**Comment by davesmith00000** [comment]
@armanbilge I've been having some fun in the PR attached.

**Comment by davesmith00000** [comment]
Will be in the next release.
