### ISSUE TITLE
Low fps when using Mutants on Windows

### ISSUE THREAD

**Issue by TiredFalcon** [PurpleKingdomGames/indigo#369]
When using Mutants:

- On Chrome 101 for macOS Monterey I get ~120 fps.
- On Chrome 100 for Windows 10 I get ~3 fps.

Which is a wild difference.
I tried recording with the devtools profiler (but I'm not at all experienced in using it) and the striking difference is that on Chrome for Windows, 98% of Self Time is attributed to getUniformBlockIndex.
On Chrome for macOS, the Self Time of the activities is spread more evenly.
I tried on Microsoft Edge and also there it's 3 fps.

Deactivating the Mutants resulted in high fps also on Windows.

This issue occurred with this game: https://gitlab.com/aronfiechter/space-survival-redux/-/tree/dev

**Comment by davesmith00000** [comment]
Have merged in the above PR, but hopefully I'll be able to try this out on a windows machine myself in the near future, so I'll leave this open for now as a reminder.

**Comment by davesmith00000** [comment]
Tested, I _think_ this is fine in so much as mutants themselves aren't a problem anymore. You can still kill performance depending on how you choose to use Mutants, but that's harder for me to do anything about.

If a new instance of this being a problem comes up, or if @TiredFalcon comes back and says there is still a problem then we'll either re-open this issue or make a new one.
