### ISSUE TITLE
BUG: Batch().tail throws exception if Batch is empty

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#388]
Related to https://github.com/PurpleKingdomGames/indigo/issues/377

Fix incoming.

**Comment by lomigmegard** [comment]
> Batch().tail throws exception

It is usually the expected behavior in Scala collection, like `List.empty.tail`, `Set.empty.tail`, etc. which all throw an `UnsupportedOperationException`.

I don't think this should change with `Batch`, the idiomatic approach would be to use `tailOption` ?

**Comment by davesmith00000** [comment]
Somehow, I did not know that. I find that really unintuitive. Weird. 🤔

**Comment by davesmith00000** [comment]
I've had a think about it, we'll stick with the current behaviour (i.e. revert the commit) to be consistent with the standard collections.

I'll put in some sort of alternative, probably with aliases because `uncons` is only useful if you know what it means.

The real fix here is to improve pattern matching, which is currently a real mess...
