### ISSUE TITLE
Logging and println not working

### ISSUE THREAD

**Issue by mattseburn** [PurpleKingdomGames/indigo#433]
I'm very new to Indigo, so I imagine I'm missing something obvious.  But, when I try to use `IndigoLogger`, or even just a simple `println` statement, I see no output in the console.  I've tried all logging methods on `IndigoLogger` as well as `println`, from several places in my (very simple) application, but the messages never appear.

Any ideas what I might be doing wrong?  Am I missing some configuration?  Are the messages being sent to a file somewhere?

**Comment by davesmith00000** [comment]
Are you looking in the browser's JavaScript console? (Open the developer tools in your browser if not.)

**Comment by mattseburn** [comment]
Hi @davesmith00000, thanks for the quick reply!

I actually just discovered in the comments on `IndigoLogger.scala` that the messages are sent to the browser's console, and then found the developer tools in the game window.  I've never used `scala.js` before, so this wasn't obvious to me.

**Comment by davesmith00000** [comment]
Don't worry! You aren't the first and won't be the last to get tripped up by that. 🙂

Do join us on our Discord if you need any help. (Click the badge on the repo homepage.)
