### ISSUE TITLE
Pointer events support

### ISSUE THREAD

**Issue by grzegorz-bielski** [PurpleKingdomGames/indigo#456]
Indigo doesn't have support for touch screens. It can be brought through [Pointer Events API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events). This implementation could also cover existing mouse support, making it a facade on top of pointer events. In the future we could also add some helpers for common gestures.

Original discussion: https://discord.com/channels/716435281208672356/716435281208672359/1069683337238691861

Will also resolve https://github.com/PurpleKingdomGames/indigo/issues/55

**Comment by davesmith00000** [comment]
Did you manage to get any further with this @grzegorz-bielski?

No pressure, I only ask because I'm hoping to cut a new release in the next couple of weeks and it would be an awesome addition. If you're not going to be ready though, don't sweat it. :smile:

**Comment by grzegorz-bielski** [comment]
Still on it! You can follow the progress on [this branch](https://github.com/grzegorz-bielski/indigo/commits/pointer-events-support).

What's left is adding some gesture handlers to make the pointers events support more useful from the get go ... and further testing.
Not sure if I'll be able to finish it for the next release though.
