### ISSUE TITLE
Add `toVertex` to `Point`

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/indigo#493]
Currently you can convert a point to a `Vector` or `Size` but not a `Vertex`. Worth adding this to the `Point` class I think :-)

**Comment by davesmith00000** [comment]
I've thought about it many times, but there is a problem. :grin: 

`Point` and `Size` and `Vector2` and so on all live in the `indigo` module, and have no knowledge of `Vertex` in the `indigo-extras` module.

So the only way to make that work is to move the `geom` package out of `indigo-extras` into `indigo`.

**Comment by davesmith00000** [comment]
This is done, will be in the next release.
