### ISSUE TITLE
Add Mouse/Pointer Enter/Leave events

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/indigo#512]
At the moment it's not possible to detect if the mouse or pointer has left the screen. This means if you're listening for a `MouseDown` event we don't know that the mouse has left the game screen (and may subsequently fire a `MouseUp` event we don't capture)

**Comment by grzegorz-bielski** [comment]
We should already have `PointerEvent.PointerEnter` and `PointerEvent.PointerLeave`. 

I guess `MouseEvent.MouseEnter` and `MouseEvent.MouseLeave` could also be added for sake of consistency, but currently mouse events in Indigo (besides `MouseEvent.Wheel`) are working on top of browser's pointer events anyway, so you can just use `PointerEnter` / `PointerLeave` and there shouldn't be a change in behavior if later `MouseEnter` / `MouseLeave` will end up in Indigo.
