### ISSUE TITLE
BUG: Drawing a triangle using `Shape.Polygon` doesn't seem to work brilliantly

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#536]
![image](https://github.com/PurpleKingdomGames/indigo/assets/908709/e8979f1e-49c3-4496-af87-43b46c124c59)

Points to mull over:

- We can't currently specify whether the Polygon is open or closed and there are no docs to say which it is.
- There's a weird line at the top, I wonder if that line has always been there and I just haven't noticed before (based on my limited test cases)?
- Is it worth adding a `Shape.Triangle` for more accurate drawing support?

**Comment by JPonte** [comment]
I have the same issue and it's not just triangles.
I'm drawing some prallelograms and it works perfectly on indigo 0.14.0 but that line started appearing when I updated to 0.15.0.

**Comment by davesmith00000** [comment]
Ah! That's a good clue though! Indigo 0.14.0 still used the old GLSL shaders, seems likely that I've just messed up the port of the polygon shader from GLSL to Scala. Thanks! :pray:

**Comment by davesmith00000** [comment]
Fixed by @JPonte :rocket: 
https://github.com/PurpleKingdomGames/indigo/pull/654
