### ISSUE TITLE
Add Touch events

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#55]
This may be slightly more involved than I'd anticipated.

MDN Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Specifications

Spec:
https://www.w3.org/TR/touch-events/#touch-interface

**Comment by grzegorz-bielski** [comment]
What about pointer events?
MDN doc: https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events
This is a slightly newer API that covers more input methods and unifies mouse and touch events.

**Comment by davesmith00000** [comment]
Thanks for the tip! I'm generally quite behind the times on the latest browser developments, always good to get some steer. 😄 

Also compatibility looks to be fine: https://caniuse.com/pointer

**Comment by davesmith00000** [comment]
Closing this as it will be superseded by @grzegorz-bielski excellent work adding pointer support.
