### ISSUE TITLE
Pathfinding does not find path

### ISSUE THREAD

**Issue by mprevel** [PurpleKingdomGames/indigo#646]
Hi,

I think the pathfinding algorithm may miss to find a valid path.

It can be reproduced with the following snippet:

```
val pathsMap: Array[Array[Char]] = // 12x12
  Array(
    Array('*', '*', '_', '_', '_', '_', '_', '_', '_', '_', '_', '_'), // 0
    Array('*', '*', '_', '_', '_', '_', '_', '_', '_', '_', '_', '_'), // 1
    Array('*', '*', '*', '*', '*', '*', '_', '_', '_', '_', '_', '_'), // 2
    Array('_', '_', '_', '_', '_', '*', '_', '_', '_', '_', '_', '_'), // 3
    Array('_', '_', '_', '_', '_', '*', '_', '_', '_', '_', '_', '_'), // 4
    Array('_', '_', '_', '_', '_', '*', '*', '*', '_', '_', '_', '_'), // 5
    Array('_', '_', '_', '_', '_', '_', '_', '*', '_', '_', '_', '_'), // 6
    Array('_', '_', '_', '_', '_', '_', '*', '*', '_', '_', '_', '_'), // 7
    Array('_', '_', '_', '_', '_', '_', '*', '_', '_', '*', '*', '*'), // 8
    Array('_', '_', '_', '_', '_', '_', '*', '_', '_', '*', '*', '*'), // 9
    Array('_', '_', '_', '_', '_', '_', '*', '*', '*', '*', '*', '*'), // 10
    Array('_', '_', '_', '_', '_', '_', '*', '*', '*', '*', '*', '*') // 11
  )

val n           = pathsMap.length // 12
val startCoords = Coords(0, 0)
val endCoords   = Coords(n - 1, n - 1)
val impassableCoords =
  for {
    x <- 0 until n
    y <- 0 until n
    if pathsMap(y)(x) == '_'
  } yield Coords(x, y)

val searchGrid = SearchGrid.generate(
  start = startCoords,
  end = endCoords,
  impassable = impassableCoords.toList,
  gridWidth = n,
  gridHeight = n
)

```

```
println(searchGrid.isValid) // true
println(searchGrid.locatePath(Dice.fromSeed(0))) // List(Coords(0,0))
```

A possible expectation is:
```
List(Point(0,0), Point(0,1), Point(0,2), Point(1,2), Point(2,2), Point(3,2), Point(4,2), Point(5,2), Point(5,3), Point(5,4), Point(5,5), Point(6,5), Point(7,5), Point(7,6), Point(7,7), Point(6,7), Point(6,8), Point(6,9), Point(6,10), Point(6,11), Point(7,11), Point(8,11), Point(9,11), Point(10,11), Point(11,11))
```

This is not blocking me since I use another algorithm of my own, but I think it may be an issue for other users. If you may consider a PR with an A* variant (generic and customizable), please, let me know.

Regards,

**Comment by davesmith00000** [comment]
In fact I'd go further and say that there's a lot of things in Indigo like this. Places where I've done the minimum to meet some small use-case I had at the time, and that I'm hoping someone will come along as say "What is this nonsense!?! :smile:" and do a better job.

The physics engine springs to mind.

Arguably, that's the underlying premise of this _entire_ Indigo project: "If I build it, they will come, and be so offended that they do a better job so that I can deprecate my version and use theirs!" :laughing:

**Comment by mprevel** [comment]
I think that's the good way. At first, the project must have some basic features to be attractive. They do not have to be the best designed or the most performant of the market but to be here for on boarding and later improvements.
Since it's hard to know what the users will want or need, it's better to focus on things when the community ask for them.

**Comment by davesmith00000** [comment]
Thank you for the excellent work, I look forward to using making use of the new path finding system!
