### ISSUE TITLE
List of pressed mouse buttons is inverted in mouse events

### ISSUE THREAD

**Issue by stefanfromm** [PurpleKingdomGames/indigo#681]
Hi,

I think I found a bug. I was wondering why my event handling logic did not hook in at

```scala
    case e: MouseEvent.Move if e.buttons.contains(LeftMouseButton) =>
      ...
```

I found the method `indigoButtons` which maps the browser mouse event model into the Indigo event model. I think its condition is wrong:

https://github.com/PurpleKingdomGames/indigo/blob/e1f600a481b940c0334666caa48e72aa14dd3941/indigo/indigo/src/main/scala/indigo/platform/events/WorldEvents.scala#L541

Should not it be:

```scala
 .filter(i => ((e.buttons >> i) & 1) == 1)
```

?

**Comment by davesmith00000** [comment]
Summoning @hobnob :smile:

**Comment by davesmith00000** [comment]
I should have also said, thanks for reporting @stefanfromm, always appreciated. :pray:

**Comment by stefanfromm** [comment]
Great to hear that! Thank you so much! I'm playing around with Indigo, because I'm searching for something to attract my children to learn programming with Scala.

**Comment by hobnob** [comment]
:genie: 

Yup, you're right that logic is definitely the wrong way around. I'll get a PR out for that now
