### ISSUE TITLE
Pointer Events: FrameContext.Pointers looses pointer positions

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/indigo#692]
`FrameContext.pointers` is meant to keep track of the current position/tilt/buttons etc of all of the pointers being used. However, currently as soon as the main pointer (in my scenario a mouse) stops moving the pointer is removed from the `Batch` of pointers. I suspect this is because we treat the pointers in a similar way to the mouse events, but it needs a bit more thinking about and tinkering with

**Comment by davesmith00000** [comment]
I've had a quick look and the implementations are very different. I think `Mouse` could do with a bit of a clean up, and `Pointers` probably needs to work a bit more like mouse does.

It would be helpful to list a couple of examples of the expected / desired behaviours. (I don't really use Pointers :sweat_smile:)
