### ISSUE TITLE
Have a way of discerning click events

### ISSUE THREAD

**Issue by hobnob** [PurpleKingdomGames/indigo#703]
At the moment click events only fire on a left mouse click, with no way to discern a right click from any other click event. We should fire the click event when a right **or** left click happen, allow discerning which button was clicked, and allow any pointer device clicks.

**Comment by davesmith00000** [comment]
I've had a look into this, two things:

1. There is no Right click, but we could latch onto the [contextmenu event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event), what do you think?
2. There is a workaround. You can listen for pointer events, like this:

```scala
    case c @ PointerEvent.PointerUp(_) =>
      println(c.button) // Tells you which button was released, e.g. : `RightMouseButton`
      Outcome(viewModel)
```
