### ISSUE TITLE
Add the ability to draw basic shapes

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/indigo#9]
An early design decision was made that Indigo would be limited to rendering images on top of images. However many times during development, it would have been useful to be able to draw at least basic but possibly arbitrary shapes and lines.

Would be good to add support at minimum for:

- Pixels
- Lines (Straight and curved)
- Rectangles
- Circles / Ovals

This is a big subject area and we don't need to solve all the possible permutations of drawing vector graphics in the first instance.

Doing this is reliant on this issue:
https://github.com/PurpleKingdomGames/indigo/issues/6 (more than one shader per layer)

**Comment by davesmith00000** [comment]
Closing - Will be in the next release.

**Comment by kag0** [comment]
Did this get released? Is there a relevant doc or PR?

**Comment by davesmith00000** [comment]
Hi @kag0, yes it did, it's in `0.7.0`.

I haven't gotten round to the docs yet I'm afraid, nor is there an official example ...but there's some sample code here if it helps:
https://github.com/PurpleKingdomGames/indigo/blob/master/indigo/sandbox/src/main/scala/com/example/sandbox/scenes/ShapesScene.scala

There's a very brief mention of it in the release notes too:
https://github.com/PurpleKingdomGames/indigo/releases/tag/v0.7.0

**Comment by kag0** [comment]
Awesome!

I haven't been able to get that working yet 😬 but I'm using Indigo for [LD48](https://ldjam.com/events/ludum-dare/48) and being able to draw rectangles for hitboxes will be very useful for debugging.

**Comment by davesmith00000** [comment]
Cool! If you hop onto the Discord server I'll be happy to help you if you get stuck? Or there is a gitter channel that literally no-one uses - but you could be the first! 😁

Links to both on the Indigo repo homepage.
